/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silo.vista.procesos;

import javax.swing.ListModel;
import org.silo.vista.componentes.CopiaListModel;
import org.silo.vista.componentes.FilteredListModel;

/**
 *
 * @author VREBO
 */
public class PanelVenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelVenta
     */
    public PanelVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jXImageView1 = new org.jdesktop.swingx.JXImageView();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        searchField = new org.jdesktop.swingx.JXSearchField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        idCopia = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        folio = new org.jdesktop.swingx.JXTextField();
        cliente = new org.jdesktop.swingx.JXTextField();
        empleado = new org.jdesktop.swingx.JXTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new org.jdesktop.swingx.JXTable();
        btnEliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cambio = new javax.swing.JTextField();
        montoPago = new javax.swing.JTextField();
        recibido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(350);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda de copias"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jXImageView1Layout = new javax.swing.GroupLayout(jXImageView1);
        jXImageView1.setLayout(jXImageView1Layout);
        jXImageView1Layout.setHorizontalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jXImageView1Layout.setVerticalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(jXImageView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 130));

        jLabel11.setText("Código:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 40, -1));

        jLabel12.setText("Título:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 40, -1));

        jLabel13.setText("Precio:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 40, -1));

        searchField.setPrompt("Buscar");
        jPanel1.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 110, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnAgregar.setText("<");
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lista);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 180, 90));

        idCopia.setText("jLabel7");
        jPanel1.add(idCopia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        titulo.setText("jLabel14");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        precio.setText("jLabel15");
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Folio:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 41, -1));

        jLabel2.setText("Cliente:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 41, -1));

        jLabel3.setText("Atiende:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel2.add(folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 100, -1));
        jPanel2.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 210, -1));
        jPanel2.add(empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 210, -1));

        jLabel4.setText("Fecha:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel5.setText("dd/MM/yyyy");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel6.setText("Detalle venta");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jScrollPane1.setViewportView(tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, 330, 120));

        btnEliminar.setText("Eliminar");
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jButton2.setText("Realizar venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel8.setText("Monto a pagar:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel9.setText("Recibido:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 70, -1));

        jLabel10.setText("Cambio:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 70, -1));
        jPanel2.add(cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 80, -1));
        jPanel2.add(montoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 80, -1));
        jPanel2.add(recibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 80, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 350, 10));

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JTextField cambio;
    private org.jdesktop.swingx.JXTextField cliente;
    private org.jdesktop.swingx.JXTextField empleado;
    private org.jdesktop.swingx.JXTextField folio;
    private javax.swing.JLabel idCopia;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private org.jdesktop.swingx.JXImageView jXImageView1;
    private javax.swing.JList lista;
    private javax.swing.JTextField montoPago;
    private javax.swing.JLabel precio;
    private javax.swing.JTextField recibido;
    private org.jdesktop.swingx.JXSearchField searchField;
    private org.jdesktop.swingx.JXTable tabla;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
    
    private void _initComponents(){
        ListModel source = new CopiaListModel();
        
        FilteredListModel filteredModel = new FilteredListModel(null);
        lista.setModel(null);
    }

}