/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silo.vista.catalogos.forms;

import org.silo.modelos.bo.Genero;

/**
 *
 * @author VREBO
 */
public class FormularioGenero extends javax.swing.JPanel implements Form<Genero>{

    /**
     * Creates new form FormularioGenero
     */
    public FormularioGenero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id = new org.jdesktop.swingx.JXTextField();
        nombre = new org.jdesktop.swingx.JXTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new org.jdesktop.swingx.JXTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        id.setEditable(false);
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, -1));

        nombre.setToolTipText("Nombre");
        nombre.setPrompt("Nombre");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 180, -1));

        descripcion.setColumns(20);
        descripcion.setLineWrap(true);
        descripcion.setRows(5);
        descripcion.setPrompt("Descripción...");
        jScrollPane1.setViewportView(descripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 370, 220));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTextArea descripcion;
    private org.jdesktop.swingx.JXTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTextField nombre;
    // End of variables declaration//GEN-END:variables

    private Genero data = new Genero();
    
    @Override
    public Genero getData() {
        data.setNombre(nombre.getText());
        data.setDescripcion(descripcion.getText());
        return data;
    }

    @Override
    public void setData(Genero data) {
        this.data = data;
        updateData();
    }

    @Override
    public void updateData() {
        id.setText(data.getIdGenero() + "");
        nombre.setText(data.getNombre());
        descripcion.setText(data.getDescripcion());
    }

    @Override
    public void cleanData() {
        id.setText("Generado");
        nombre.setText("");
        descripcion.setText("");
    }
}
