package org.silo.vista.catalogos.forms;

import java.util.Date;
import javax.swing.JComboBox;
import org.silo.modelos.bo.Genero;
import org.silo.modelos.bo.Pelicula;

public class FormularioPelicula extends javax.swing.JPanel implements Form<Pelicula> {

    /**
     * Creates new form FormularioPelicula
     */
    public FormularioPelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new org.silo.vista.componentes.ImagePanel();
        id = new org.jdesktop.swingx.JXTextField();
        titulo = new org.jdesktop.swingx.JXTextField();
        director = new org.jdesktop.swingx.JXTextField();
        estelares = new org.jdesktop.swingx.JXTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        duracion = new javax.swing.JSpinner();
        anioEstreno = new javax.swing.JSpinner();
        genero = new javax.swing.JComboBox();
        clasificacion = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(420, 300));
        setPreferredSize(new java.awt.Dimension(420, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(imagePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        id.setEditable(false);
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, -1));

        titulo.setPrompt("Título");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, -1));

        director.setPrompt("Director");
        add(director, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));

        estelares.setPrompt("Estelares");
        add(estelares, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, -1));

        jLabel1.setText("ID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Duración:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setText("Año de estreno:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel4.setText("Género:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel5.setText("Clasificación:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        duracion.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        duracion.setEditor(new javax.swing.JSpinner.DateEditor(duracion, "hh:mm"));
        add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 90, -1));

        anioEstreno.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(-946617600000L), null, java.util.Calendar.YEAR));
        anioEstreno.setEditor(new javax.swing.JSpinner.DateEditor(anioEstreno, "yyyy"));
        add(anioEstreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, -1));

        genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, -1));

        clasificacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "B15", "C", "D" }));
        add(clasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 80, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner anioEstreno;
    private javax.swing.JComboBox clasificacion;
    private org.jdesktop.swingx.JXTextField director;
    private javax.swing.JSpinner duracion;
    private org.jdesktop.swingx.JXTextField estelares;
    private javax.swing.JComboBox genero;
    private org.jdesktop.swingx.JXTextField id;
    private org.silo.vista.componentes.ImagePanel imagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private org.jdesktop.swingx.JXTextField titulo;
    // End of variables declaration//GEN-END:variables

    private Pelicula data = new Pelicula();

    @Override
    public Pelicula getData() {
        data.setTitulo(titulo.getText());
        data.setDirector(director.getText());
        data.setEstelares(estelares.getText());
        data.setDuracion((Date) duracion.getValue());
        data.setAnioEstreno((Date) anioEstreno.getValue());
        data.setGenero((Genero) genero.getSelectedItem());
        data.setClasificacion((String) clasificacion.getSelectedItem());
        data.setImagen(imagePanel1.getData());
        return data;
    }

    @Override
    public void setData(Pelicula data) {
        this.data = data;
        updateData();
    }

    @Override
    public void updateData() {
        id.setText(data.getIdPelicula() + "");
        titulo.setText(data.getTitulo());
        director.setText(data.getDirector());
        estelares.setText(data.getEstelares());
        duracion.setValue(data.getDuracion());
        anioEstreno.setValue(data.getAnioEstreno());
        genero.setSelectedItem(data.getGenero());
        clasificacion.setSelectedItem(data.getClasificacion());
        imagePanel1.setData(data.getImagen());
    }

    @Override
    public void cleanData() {
        id.setText("Generado");
        titulo.setText("");
        director.setText("");
        estelares.setText("");
        duracion.setValue(new Date());
        anioEstreno.setValue(new Date());
        if (genero.getModel().getSize() > 0) {
            genero.setSelectedIndex(0);
        }
        clasificacion.setSelectedIndex(0);
        imagePanel1.cleanData();
    }

    public JComboBox getGenero() {
        return genero;
    }

}
