package org.silo.vista.catalogos.forms;

import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import org.jdesktop.swingx.JXImageView;
import org.silo.modelos.bo.CopiaPelicula;
import org.silo.modelos.bo.Pelicula;
import org.silo.utils.ImageUtils;
import org.silo.vista.componentes.ImagePanel;

public class FormularioCopia extends javax.swing.JPanel implements Form<CopiaPelicula> {

    /**
     * Creates new form FormularioCopia
     */
    public FormularioCopia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id = new org.jdesktop.swingx.JXTextField();
        precio = new org.jdesktop.swingx.JXTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JComboBox();
        formato = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        fechaAdquisicion = new org.silo.vista.componentes.JXDatePicker();
        estado = new javax.swing.JComboBox();
        jXImageView1 = new org.jdesktop.swingx.JXImageView();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, -1));

        precio.setToolTipText("Precio");
        precio.setPrompt("Precio");
        add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));

        jLabel2.setText("Fecha de adquisición:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel3.setText("Formato:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        titulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Título" }));
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, -1));

        formato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DVD", "BLURAY" }));
        add(formato, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, -1));

        jLabel6.setText("Estado:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        add(fechaAdquisicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 110, -1));

        estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EN-STOCK", "VENDIDA", "DAÑADA" }));
        add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 110, -1));
        add(jXImageView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 150, 150));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox estado;
    private org.silo.vista.componentes.JXDatePicker fechaAdquisicion;
    private javax.swing.JComboBox formato;
    private org.jdesktop.swingx.JXTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private org.jdesktop.swingx.JXImageView jXImageView1;
    private org.jdesktop.swingx.JXTextField precio;
    private javax.swing.JComboBox titulo;
    // End of variables declaration//GEN-END:variables

    private CopiaPelicula data = new CopiaPelicula();

    @Override
    public CopiaPelicula getData() {
        data.setPelicula((Pelicula) titulo.getSelectedItem());
        data.setPrecio(Double.parseDouble(precio.getText()));
        data.setEstado(estado.getSelectedItem().toString());
        data.setFormato(formato.getSelectedItem().toString());
        data.setFechaAdquisicion(fechaAdquisicion.getDate());
        return data;
    }

    @Override
    public void setData(CopiaPelicula data) {
        this.data = data;
        updateData();
    }

    @Override
    public void updateData() {
        id.setText(data.getIdCopiaPelicula() + "");
        titulo.setSelectedItem(data.getPelicula());
        precio.setText(data.getPrecio() + "");
        fechaAdquisicion.setDate(data.getFechaAdquisicion());
        formato.setSelectedItem(data.getFormato());
        estado.setSelectedItem(data.getEstado());
        jXImageView1.setImage(ImageUtils.minimizeImage(data.getPelicula().getImagen().getImagen()));
    }

    @Override
    public void cleanData() {
        id.setText("Generado");
        titulo.setSelectedItem(0);
        precio.setText("");
        fechaAdquisicion.setDate(new Date());
        formato.setSelectedItem(0);
        estado.setSelectedItem(0);
        jXImageView1.setImage(ImageUtils.minimizeImage(new ImageIcon("resources/images/Silo3A-ico2.png")));
    }

    public JComboBox getTitulo() {
        return titulo;
    }

    public JXImageView getjXImageView1() {
        return jXImageView1;
    }

}
