/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silo.vista.catalogos;

import javax.swing.table.TableModel;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author VREBO
 */
public class TablaPanel extends javax.swing.JPanel {

    /**
     * Creates new form TablaPanel
     */
    public TablaPanel() {
        initComponents();
        jXTable.setColumnControlVisible(true);
        jXTable.packAll();
        jXTable.setHorizontalScrollEnabled(true);
    }
    
    public TablaPanel(TableModel modelo){
        this();
        jXTable.setModel(modelo);
    }

    public JXTable getjXTable() {
        return jXTable;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable = new org.jdesktop.swingx.JXTable();

        setMaximumSize(new java.awt.Dimension(420, 300));
        setMinimumSize(new java.awt.Dimension(420, 200));
        setPreferredSize(new java.awt.Dimension(420, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jXTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 199));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTable;
    // End of variables declaration//GEN-END:variables
}
