/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silo.vista.reportes;

import java.util.Date;
import org.silo.vista.catalogos.forms.Form;

/**
 *
 * @author VREBO
 */
public class GeneradorReporteCliente extends javax.swing.JPanel implements Form<Date[]>{

    /**
     * Creates new form GeneradorReporteCliente
     */
    public GeneradorReporteCliente() {
        initComponents();
        _initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        fin = new javax.swing.JSpinner();
        inicio = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setText("Último mes");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jRadioButton2.setText("Definir intervalo");
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Intervalo del reporte:"), javax.swing.BorderFactory.createEtchedBorder()));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fin.setModel(new javax.swing.SpinnerDateModel());
        fin.setEditor(new javax.swing.JSpinner.DateEditor(fin, "dd/MM/yyyy"));
        jPanel1.add(fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 80, -1));

        inicio.setModel(new javax.swing.SpinnerDateModel());
        inicio.setEditor(new javax.swing.JSpinner.DateEditor(inicio, "dd/MM/yyyy"));
        jPanel1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 80, -1));

        jLabel1.setText("Inicio:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setText("Fin:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged
        // TODO add your handling code here:
        boolean x = true;
        if (jRadioButton2.isSelected()) {
            x = false;
        }
        inicio.setEnabled(x);
        fin.setEnabled(x);
    }//GEN-LAST:event_jRadioButton2StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JSpinner fin;
    private javax.swing.JSpinner inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables

    private void _initComponents() {
        jRadioButton1.setSelected(true);
        buttonGroup.add(jRadioButton1);
        buttonGroup.add(jRadioButton2);
    }
private Date[] data = new Date[2];
    
    @Override
    public Date[] getData() {
        data[0] = (Date) inicio.getValue();
        data[1] = (Date) fin.getValue();
        return data;
    }

    @Override
    public void setData(Date[] data) {
        this.data = data;
    }

    @Override
    public void updateData() {
        inicio.setValue(data[0]);
        fin.setValue(data[1]);
    }

    @Override
    public void cleanData() {
        inicio.setValue(new Date());
        fin.setValue(new Date());
    }
    
    @Override
    public void setEnabled(boolean value){
        super.setEnabled(value);
        inicio.setEnabled(value);
        fin.setEnabled(value);
    }
}