/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silo.vista.reportes;

import java.util.Date;
import org.silo.vista.catalogos.forms.Form;

/**
 *
 * @author VREBO
 */
public class PanelClientes extends PanelGenerador implements Form<Date[]>{

    /**
     * Creates new form PanelClientes
     */
    public PanelClientes() {
        initComponents();
        nombreReporte = "reporte-clientes";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIntervaloFecha1 = new org.silo.vista.reportes.PanelIntervaloFecha();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reporte de registro de clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        setLayout(new java.awt.BorderLayout());
        add(panelIntervaloFecha1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.silo.vista.reportes.PanelIntervaloFecha panelIntervaloFecha1;
    // End of variables declaration//GEN-END:variables

    private Date [] data = null;
    
    @Override
    public Date[] getData() {
        return panelIntervaloFecha1.getData();
    }

    @Override
    public void setData(Date[] data) {
        this.data = data;
        updateData();
    }

    @Override
    public void updateData() {
        panelIntervaloFecha1.setData(data);
    }

    @Override
    public void cleanData() {
        
    }

}
