/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silo.vista.reportes;

/**
 *
 * @author VREBO
 */
public class PanelGenerador extends javax.swing.JPanel {

    protected String nombreReporte;
    /**
     * Creates new form PanelGenerador
     */
    public PanelGenerador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generadorToolBar1 = new org.silo.vista.componentes.GeneradorToolBar();

        setLayout(new java.awt.BorderLayout());

        generadorToolBar1.setRollover(true);
        add(generadorToolBar1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.silo.vista.componentes.GeneradorToolBar generadorToolBar1;
    // End of variables declaration//GEN-END:variables

    public String getNombreReporte() {
        return nombreReporte;
    }

}
