/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silo.vista.reportes;

import java.util.Date;
import org.silo.vista.catalogos.forms.Form;

/**
 *
 * @author VREBO
 */
public class PanelVentas extends PanelGenerador implements Form<Object[]> {

    /**
     * Creates new form PanelVentas
     */
    public PanelVentas() {
        initComponents();
        nombreReporte = "reporte-ventas";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        panelIntervaloFecha1 = new org.silo.vista.reportes.PanelIntervaloFecha();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reporte de ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setText("Agrupar resultados por empleado");
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 256, -1, -1));
        add(panelIntervaloFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 28, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private org.silo.vista.reportes.PanelIntervaloFecha panelIntervaloFecha1;
    // End of variables declaration//GEN-END:variables
    private Object[] data = null;

    @Override
    public Object[] getData() {
        boolean agrupar = jCheckBox1.isSelected();
        Date[] intervalo = panelIntervaloFecha1.getData();
        return new Object[]{agrupar, intervalo};
    }

    @Override
    public void setData(Object[] data) {
        updateData();
    }

    @Override
    public void updateData() {
        jCheckBox1.setSelected((boolean) data[0]);
        panelIntervaloFecha1.setData((Date[]) data[1]);
    }

    @Override
    public void cleanData() {
    }

}
