/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silo.vista.reportes;

import java.util.Calendar;
import java.util.Date;
import org.silo.vista.catalogos.forms.Form;

/**
 *
 * @author VREBO
 */
public class PanelIntervaloFecha extends javax.swing.JPanel implements Form<Date[]> {

    /**
     * Creates new form GeneradorReporteCliente
     */
    public PanelIntervaloFecha() {
        initComponents();
        _initComponents();
        cleanData();
        setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        fechaDefault = new javax.swing.JRadioButton();
        intervalo = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        fin = new javax.swing.JSpinner();
        inicio = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechaDefault.setText("Último mes");
        add(fechaDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        intervalo.setText("Definir intervalo");
        intervalo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                intervaloStateChanged(evt);
            }
        });
        add(intervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Intervalo del reporte:"), javax.swing.BorderFactory.createEtchedBorder()));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fin.setModel(new javax.swing.SpinnerDateModel());
        fin.setEditor(new javax.swing.JSpinner.DateEditor(fin, "dd/MM/yyyy"));
        jPanel1.add(fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 80, -1));

        inicio.setModel(new javax.swing.SpinnerDateModel());
        inicio.setEditor(new javax.swing.JSpinner.DateEditor(inicio, "dd/MM/yyyy"));
        jPanel1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 80, -1));

        jLabel1.setText("Inicio:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setText("Fin:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void intervaloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_intervaloStateChanged
        // TODO add your handling code here:
        boolean x = false;
        if (intervalo.isSelected()) {
            x = true;
        }
        inicio.setEnabled(x);
        fin.setEnabled(x);
    }//GEN-LAST:event_intervaloStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton fechaDefault;
    private javax.swing.JSpinner fin;
    private javax.swing.JSpinner inicio;
    private javax.swing.JRadioButton intervalo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void _initComponents() {
        fechaDefault.setSelected(true);
        buttonGroup.add(fechaDefault);
        buttonGroup.add(intervalo);
    }
    private Date[] data = new Date[2];

    @Override
    public Date[] getData() {
        if (fechaDefault.isSelected()) {
            Calendar c = Calendar.getInstance();
            c.add(Calendar.MONTH, -1);
            data[0] = c.getTime();
            data[1] = new Date();
            System.out.println("ultimo mes");
        } else {
            data[0] = (Date) inicio.getValue();
            data[1] = (Date) fin.getValue();
        }
        System.out.println(data[0]);
        System.out.println(data[1]);
        return data;
    }

    @Override
    public void setData(Date[] data) {
        this.data = data;
    }

    @Override
    public void updateData() {
        inicio.setValue(data[0]);
        fin.setValue(data[1]);
    }

    @Override
    public void cleanData() {
        Calendar c = Calendar.getInstance();
        c.add(Calendar.MONTH, -1);
        inicio.setValue(c.getTime());
        fin.setValue(new Date());
    }

    @Override
    public void setEnabled(boolean value) {
        super.setEnabled(value);
        inicio.setEnabled(value);
        fin.setEnabled(value);
    }
}
