/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silo.vista.reportes;

import java.util.Date;
import org.silo.vista.catalogos.forms.Form;

/**
 *
 * @author VREBO
 */
public class PanelEmpleados extends PanelGenerador implements Form<Object[]> {

    /**
     * Creates new form PanelEmpleados
     */
    public PanelEmpleados() {
        initComponents();
        nombreReporte = "reporte-empleado";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIntervaloFecha1 = new org.silo.vista.reportes.PanelIntervaloFecha();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reporte de registro de empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jCheckBox1.setText("Agrupar resultados por condición.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelIntervaloFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelIntervaloFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(0, 36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private org.silo.vista.reportes.PanelIntervaloFecha panelIntervaloFecha1;
    // End of variables declaration//GEN-END:variables

    Object[] data = null;

    @Override
    public Object[] getData() {
        boolean agrupar = jCheckBox1.isSelected();
        Date[] intervalo = panelIntervaloFecha1.getData();
        return new Object[]{agrupar, intervalo};
    }

    @Override
    public void setData(Object[] data) {
        updateData();
    }

    @Override
    public void updateData() {
        jCheckBox1.setSelected((boolean) data[0]);
        panelIntervaloFecha1.setData((Date[]) data[1]);
    }

    @Override
    public void cleanData() {
    }

}
