/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silo.vista.componentes;

import org.silo.vista.catalogos.forms.Form;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.silo.modelos.bo.Imagen;

/**
 *
 * @author VREBO
 */
public class ImagePanel extends javax.swing.JPanel implements Form<Imagen> {

    /**
     * Creates new form ImagePanel
     */
    public ImagePanel() {
        initComponents();
        _initComponets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jXImageView1 = new org.jdesktop.swingx.JXImageView();

        jButton1.setText("Examinar...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXImageView1Layout = new javax.swing.GroupLayout(jXImageView1);
        jXImageView1.setLayout(jXImageView1Layout);
        jXImageView1Layout.setHorizontalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jXImageView1Layout.setVerticalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXImageView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jXImageView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadImage();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private org.jdesktop.swingx.JXImageView jXImageView1;
    // End of variables declaration//GEN-END:variables

    private Imagen data;

    private void _initComponets() {
        jXImageView1.setDragEnabled(false);
    }

    private void loadImage() {
        JFileChooser fc = new JFileChooser();
        fc.addChoosableFileFilter(new ImageFilter());
        fc.setAcceptAllFileFilterUsed(false);

        //Add custom icons for file types.
        fc.setFileView(new ImageFileView());

        //Add the preview pane.
        fc.setAccessory(new ImagePreview(fc));

        int opcion = fc.showDialog(this, "Cargar");
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            data = new Imagen(file,
                              new ImageIcon(file.getPath()));
            updateData();
        }
    }

    private Image minimizeImage(ImageIcon tmpIcon) {
        if (tmpIcon.getIconWidth() > 150) {
            tmpIcon = new ImageIcon(tmpIcon.getImage().
                    getScaledInstance(150, -1,
                                      Image.SCALE_DEFAULT));
        }
        if (tmpIcon.getIconHeight() > 150) {
            tmpIcon = new ImageIcon(tmpIcon.getImage().
                    getScaledInstance(-1, 150,
                                      Image.SCALE_DEFAULT));
        }
        return tmpIcon.getImage();
    }

    @Override
    public Imagen getData() {
        return data;
    }

    @Override
    public void setData(Imagen data) {
        this.data = data;
        updateData();
    }

    @Override
    public void updateData() {
        jXImageView1.setImage(minimizeImage(data.getImagen()));
    }

    @Override
    public void cleanData() {
        File file = new File("resources/images/Silo3-ico2.png");
        System.out.println(file.canRead());
        data = new Imagen(file,
                              new ImageIcon(file.getPath()));
        updateData();
    }
}
